Config = {
    'TRAIN_BS': 4,
    'VALID_BS': 1,
    #'IMG_SIZE': (224, 224),
    'IMG_SIZE': (1024, 1024),
    #'MODEL_NAME': 'swin_base_patch4_window7_224',
    'MODEL_NAME': 'efficientnet_b1',
    #'MODEL_NAME': 'resnet50',
    'NUM_WORKERS': 8,
    #'PARENT_PATH': '/kaggle/input/rsna-mammography-images-as-pngs/images_as_pngs_cv2_384/train_images_processed_cv2_384/',
    #'PARENT_PATH': '/fast/rsna-breast/512-png-ext-imagenet',
    'PARENT_PATH': '/fast/rsna-breast/1024-png-ext/train_images_processed_cv2_dicomsdl_1024/',
    'FILE_PATH': '/kaggle/input/rsna-breast-cancer-detection/train.csv',
    'LOSS': 'BCEWithLogitsLoss',
    'EVAL_METRIC': 'F1',
    'NB_EPOCHS': 2,
    'SPLITS': 5,
    'min_lr': 1e-6,
    'T_max': 20,
    'T_0': 25,
    'fc_dropout': 0.2,
    'betas': (0.9, 0.999),
    'NUM_LABELS': 1,
    'LR': 2e-4,
    'competition': 'rsna_mammography',
    '_wandb_kernel': 'tanaym',
}

